language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install coveralls
  - pip install codecov
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - sudo apt-get install graphviz
  - pip install .
  - pip install .[viz]
  - pip install .[test]
script:
  - python -m pytest --runslow
  - py.test --runslow --cov=./
branches:
  only:
    - master
    - dev
after_success:
    - coveralls
    # - codecov